### ISSUE TITLE
Lot of issues making this work. Now: EOFError: Ran out of input

### ISSUE THREAD

**Issue by venturaEffect** [rese1f/StableVideo#15]
Hi,

I'm not a pro dev and I have to say that the readme is quite ambiguous for example how to install Controlnet, just some generic link where it doesn't tell much. The the other link to a github repo for training with your videos. Nothing really explaining of how to do it.

It would be great to appreciate your work if it could be more clear how to run it.

I'm stuck on running the python app.py. I get an error that tried to solve but nothing seems to work. This is the error message: 

`...
Setting up MemoryEfficientCrossAttention. Query dim is 1280, context_dim is 768 and using 8 heads.
Loaded model config from [ckpt/cldm_v15.yaml]
Traceback (most recent call last):
  File "C:\Users\zaesa\StableVideo\app.py", line 358, in <module>
    stablevideo.load_canny_model()
  File "C:\Users\zaesa\StableVideo\app.py", line 51, in load_canny_model
    canny_model.load_state_dict(load_state_dict(canny_model_cfg, location='cuda'), strict=False)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\StableVideo\cldm\model.py", line 18, in load_state_dict
    state_dict = get_state_dict(torch.load(ckpt_path, map_location=torch.device(location)))
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\anaconda3\envs\stablevideo\Lib\site-packages\torch\serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\zaesa\anaconda3\envs\stablevideo\Lib\site-packages\torch\serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: Ran out of input`

Any help will be really appreciated. And if you can please make more clear the readme. It isn't really done to help people test the code.

Thanks

**Comment by wenhaochai** [comment]
As for install controlnet, the weights should be download and place following in the structure shown in README.md, then the weights can be loaded
