### ISSUE TITLE
RuntimeError: The size of tensor a (998) must match the size of tensor b (992) at non-singleton dimension 3

### ISSUE THREAD

**Issue by Pythonpa** [rese1f/StableVideo#8]
when I ran the "black swan" demo, and it has some problem occurs, **[hers is the error message:]**,how to resolve it?
Traceback (most recent call last):
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/gradio/routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/gradio/blocks.py", line 1431, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/gradio/utils.py", line 706, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "/home/pymo/miniconda3/envs/stablevideo/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/pymo/StableVideo/app.py", line 300, in render
    f_atlas = f_atlas * (1 - mask) + f_atlas_origin * mask
                                     ~~~~~~~~~~~~~~~^~~~~~
RuntimeError: The size of tensor a (998) must match the size of tensor b (992) at non-singleton dimension 3

**Comment by Pythonpa** [comment]
> @Pythonpa please see the pull request, [lwneal](https://github.com/lwneal) give a solution about this. It doesn't happen in my own device :(

ok, thanks for your reply
