### ISSUE TITLE
AttributeError: 'torch.dtype' object has no attribute 'char'

### ISSUE THREAD

**Issue by magicwang1111** [rese1f/StableVideo#9]
Model has 264706 params
Model has 133122 params
Model has 416379 params
Model has 416379 params
Model has 402945 params
C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\components\video.py:334: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4
  warnings.warn(
Error converting video to browser-playable format `ffmpeg -y -loglevel quiet -i C:\Users\admin\AppData\Local\Temp\tmpwoitac9w data\bear\bear.mp4` exited with status 1

STDOUT:

STDERR:

Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\StableVideo\app.py", line 344, in render
    imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\tifffile\tifffile.py", line 1946, in write
    data, byteorder + data.dtype.char, 'C'
AttributeError: 'torch.dtype' object has no attribute 'char'
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\StableVideo\app.py", line 344, in render
    imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\tifffile\tifffile.py", line 1946, in write
    data, byteorder + data.dtype.char, 'C'
AttributeError: 'torch.dtype' object has no attribute 'char'
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\StableVideo\app.py", line 344, in render
    imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\tifffile\tifffile.py", line 1946, in write
    data, byteorder + data.dtype.char, 'C'
AttributeError: 'torch.dtype' object has no attribute 'char'
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\StableVideo\app.py", line 344, in render
    imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\tifffile\tifffile.py", line 1946, in write
    data, byteorder + data.dtype.char, 'C'
AttributeError: 'torch.dtype' object has no attribute 'char'
Traceback (most recent call last):
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1435, in process_api
    result = await self.call_function(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\blocks.py", line 1107, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "F:\StableVideo\app.py", line 344, in render
    imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\v2.py", line 495, in mimwrite
    return file.write(ims, is_batch=True, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\imageio\plugins\tifffile_v3.py", line 244, in write
    self._fh.write(image, **kwargs)
  File "C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\tifffile\tifffile.py", line 1946, in write
    data, byteorder + data.dtype.char, 'C'
AttributeError: 'torch.dtype' object has no attribute 'char'
![image](https://github.com/rese1f/StableVideo/assets/131337141/bcb4740a-7cfe-4073-a551-d5d5f7b19365)

**Comment by rese1f** [comment]
1. seems like u can firsr edit then render
2. check if u r successfully install ffmpeg
hope those would help :)

**Comment by magicwang1111** [comment]
> 1. seems like u can firsr edit then render似乎你可以先编辑然后渲染
> 2. check if u r successfully install ffmpeg检查你是否成功安装 ffmpeg
>    hope those would help :)希望这些会有所帮助:)
1.i have edited first.
2.i have installed ffmpeg and add it to environment path.
![image](https://github.com/rese1f/StableVideo/assets/131337141/6ee26517-e0b0-49ee-aa7d-d449967cc1b5)
![image](https://github.com/rese1f/StableVideo/assets/131337141/d44e58c7-47b9-49a9-a480-866635630875)

**Comment by rese1f** [comment]
sry I have not test it on Windows system, try to modify this line
```
imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
```
to
```
imageio.mimwrite(save_name, ((255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1)).numpy())
```
If anyone meets the same issue on Windows, plz help

**Comment by magicwang1111** [comment]
> sry I have not test it on Windows system, try to modify this line
> 
> ```
> imageio.mimwrite(save_name, (255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1))
> ```
> 
> to
> 
> ```
> imageio.mimwrite(save_name, ((255 * output_video.detach().cpu()).to(torch.uint8).permute(0, 2, 3, 1)).numpy())
> ```
> 
> If anyone meets the same issue on Windows, plz help

thx，it have improve. but still have problem.
C:\Users\admin\anaconda3\envs\stablevideo\lib\site-packages\gradio\components\video.py:334: UserWarning: Video does not have browser-compatible container or codec. Converting to mp4
![image](https://github.com/rese1f/StableVideo/assets/131337141/c85ec46c-19cc-4090-a81f-ac55d0281be9)

**Comment by rese1f** [comment]
good bear :)
that's not a big problem, i found the solution [here](https://www.stellarinfo.com/blog/fix-unsupported-video-codec-error/), good luck
